// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udewilzaiyzgqhfwwfup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZXdpbHphaXl6Z3FoZnd3ZnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwODM3MzksImV4cCI6MjA1MTY1OTczOX0.xwqMHgVXgh4l-WqZDpA09TsBaup_wSVrecRevQwPTFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);